environment: "development"

server:
  port: "8080"
  host: "0.0.0.0"
  mode: "development"
  read_timeout: 10 # seconds
  write_timeout: 10 # seconds

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "myapp"
  sslmode: "disable"
  max_conns: 20
  min_conns: 1

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  max_retries: 3
  pool_size: 100
  min_idle_conns: 10
  dial_time_out: 1
  read_time_out: 1
  write_time_out: 1
  idle_time_out: 1

jwt:
  secret: "your-super-secret-key-should-be-at-least-32-chars"
  expire_hour: 24
  refresh_expire_day: 7

log_level: "info"

arango:
  db_name: "arangodb"
  conn_strs: "http://127.0.0.1:8529"
  insecure_skip_verify: true
  user: "root"
  password: "rootpassword"

clickhouse:
  host: "localhost"
  port: "9000"
  user: "default"
  password: "password"
  database: "default"
  max_open_conns: 10
  max_idle_conns: 5
  debug: true

# You will only need this in production.
logger:
  level: "info"
  encoder_config:
    message_key: "msg"
    level_key: "level"
    name_key: "logger"
  rotation_config:
    filename: "var/lib/test.txt"
    max_size: 500
    max_backups: 2
    max_age: 1
  fluentbit_config:
    host: "127.0.0.1"
    port: 24224
    tag: "test.template"

tracer:
  service_name: "test"
  insecure: "true"
  collector_url: "localhost:4317"

grpc:
  grpc_host: "localhost"
  grpc_port: "50051"
